### ISSUE TITLE
Oreo

### ISSUE THREAD

**Issue by therealsh** [hoshsadiq/bravia-youview-player-launchers#1]
hi there, using your APK to show iPlayer, All4 etc.
Was working fine on Android 7. Now with the new Sony update to Oreo, after installing your APK only iPlayer is showing, while all the rest are not there...
Any chances you can have a look?
Thanks!

**Comment by Minxster** [comment]
Just wanted to off thanks for this app. Really solved my viewing issues as I use HDHomeRuns only. But I'm having the same issue as therealsh.

**Comment by hoshsadiq** [comment]
Hi, thanks for your interest. Unfortunately I do not have a Sony Bravia that I can test against to find a solution. Really sorry but until I get a new oreo based Sony Bravia I won't be able to help.
