### ISSUE TITLE
ITV Hub won't play ITV1.

### ISSUE THREAD

**Issue by Budge669** [hoshsadiq/bravia-youview-player-launchers#10]

**Comment by Budge669** [comment]
Keeps asking me to enter my postcode.

**Comment by hoshsadiq** [comment]
That's an requirement for the ITV app. That's nothing to do with this app. If it's not accepting your post code (as in, it still asks you after you've typed in your post code), it's likely a bug on their webapp. Wait a little bit for it to get updated or contact ITV and report it as a bug.
