### ISSUE TITLE
UKTV activation

### ISSUE THREAD

**Issue by jasmine-n** [hoshsadiq/bravia-youview-player-launchers#14]
Hi Hosh

I installed the UKPlay launcher on my Sony KD-49XF9005. It opens, but after briefly showing the splash screen, hangs with a spinning blue circle.

It appears that UKTV now require you create an account and activate your TV using a code that’s displayed when opening the app. I’m guessing that is what’s going wrong.

I'm not sure if it's something you would be able to fix, but it would be great if you can!

**Comment by hoshsadiq** [comment]
I'm not sure what you mean. Could you post a screenshot?

**Comment by markhats** [comment]
I'm finding the same. Just get this after the initial splash:

![Screenshot](https://user-images.githubusercontent.com/3472245/79672959-2576a500-81ce-11ea-9fcd-adca009b3538.JPG)

**Comment by hoshsadiq** [comment]
This looks like an issue with the website. Nothing I can do about that unfortunately. Are you able to post the logcat?

**Comment by markhats** [comment]
Not sure I know how to do that. I'll see if I can look into it though.

Interestingly the link you are using which I believe to be:

https://tvapp.uktv.co.uk/?brand=default&amp;model=fvp&amp;launch_mode=video_only&amp;house_num=None

also gives the same output in the Chrome browser on my Android phone. However, it does work on my desktop machine. Not sure it that sheds any more light on it?

Thanks

**Comment by markhats** [comment]
Actually, I was wrong on that one. It doesn't work in Chrome on my desktop either. It seems to be the. `launch_mode=video_only` bit that makes it fail. If I remove that, the page loads OK.

**Comment by hoshsadiq** [comment]
Please try attached file and see if it works. I've removed `launch_mode=video_only`. I did try it in chrome and firefox with and without that, and it works fine for me either way. 

[app-uktvPlay-debug.apk.zip](https://github.com/hoshsadiq/bravia-youview-player-launchers/files/4525163/app-uktvPlay-debug.apk.zip)

Note this is a debug release, so please let me know when if it works and I'll create a release.

**Comment by markhats** [comment]
Great - all seems to work now.

Many thanks!

**Comment by hoshsadiq** [comment]
Great. I will push the changes and make a release later today.

**Comment by hoshsadiq** [comment]
I've just created a new release, [v2.3.1](https://github.com/hoshsadiq/bravia-youview-player-launchers/releases/tag/v2.3.1), once the pipeline runs it should automatically upload the apk files.
