### ISSUE TITLE
BBC Sounds

### ISSUE THREAD

**Issue by Fhilz** [hoshsadiq/bravia-youview-player-launchers#15]
Would it be possible to add BBC Sounds which is now avaiable via Sony Select ?
Many thanks

**Comment by hoshsadiq** [comment]
Hi, I can do, but I'll need the logs of when you start it, as that will tell me what the URL is for it. Please see [here](https://android.tutorials.how/adb-commands/). All you need to do is enable debugging, connect to your TV (the website seems to seems to only show using USB, but might be able to connect over your network simply by doing `adb connect <ipaddress>:5555`, then run `adb logcat` and send the logs over. You should use something like pastebin and paste the link.

**Comment by Fhilz** [comment]
Many thanks Hosh.

Looks like:

https://www.live.bbctvapps.co.uk/tap/sounds

**Comment by hoshsadiq** [comment]
Can you try attached file and see if it runs correctly?

[app-bbcSounds-debug.apk.zip](https://github.com/hoshsadiq/bravia-youview-player-launchers/files/4536562/app-bbcSounds-debug.apk.zip)

**Comment by Fhilz** [comment]
Many thanks Hosh - that works perfectly.

**Comment by hoshsadiq** [comment]
Perfect. Since that's a debug release, please download the latest version from the releases page. Currently it's [v2.4.0](https://github.com/hoshsadiq/bravia-youview-player-launchers/releases/tag/v2.4.0).

**Comment by Fhilz** [comment]
That's really great Hosh - many thanks again.
