### ISSUE TITLE
My5 links to older app

### ISSUE THREAD

**Issue by simonv74** [hoshsadiq/bravia-youview-player-launchers#18]
Installed the latest My5 app link apk, this opens an older version of My5 than the one that opens from within the Youview app.

It's no complaint, either app work fine.

These links are brilliant, it means all apps are available from the app drawer now, why Sony don't allow this by default is very annoying, so great work for providing these apks!

**Comment by hoshsadiq** [comment]
If you have adb set up and post logcat output, i may be able to update the my5 link

**Comment by hoshsadiq** [comment]
Closing due to no response. Feel free to reopen.

**Comment by simonv74** [comment]
Hi, I need to reopen this, the older version of My5 that the APK links to is being closed down by Channel 5 on 15 October so I could do with the link being changed to the newer version hidden in the system.

I will try to link to the TV with ADB and get the logcat output, I may need to come back to you if Google isn't my friend!

**Comment by hoshsadiq** [comment]
Sure, please set up adb, start logcat, and then open the real my5 app (the one provided with YouView). Lastly, stop logcat, then copy the logs and upload them somewhere and post here (you can use https://gist.github.com).

**Comment by simonv74** [comment]
Hi,

Thanks for that, I've uploaded the logs to here: https://gist.github.com/simonv74/6ecbf2fe5049b88fce9d4a9af98ae9c8

**Comment by simonv74** [comment]
10-14 11:12:58.763 25084 25084 E HbbTVLauncher: NativeAppMtkTVCallbackHandler: Constructor called w/com.sony.dtv.hbbtvlauncher.LaunchHbbTV@154d35e
10-14 11:12:58.764 25084 25084 E HbbTVLauncher: handleHbbTvLaunch: Launch app w/param = type=bi, service=BBC_Sports, url=https://c5apps.channel5.com/my5youview/index.html

I think that might be the part you need but could be wrong!

**Comment by hoshsadiq** [comment]
Think that's right. I will double check later and hopefully cut a release..

**Comment by simonv74** [comment]
Excellent - many thanks

**Comment by hoshsadiq** [comment]
This is updated in 2.5.0

**Comment by Mrmad1966** [comment]
Yes seen that. Thank you so much
