### ISSUE TITLE
UKTV app closes during ads

### ISSUE THREAD

**Issue by Grogman32** [hoshsadiq/bravia-youview-player-launchers#19]
I've got the UKTV apk from the 2.4.0 release installed on a KD-49X8309C. When watching a show, it will play the first ad roll, the video will play just fine, then when it goes to an ad break, the app will close to the home screen. Tried on my phone and there's no issues with the ads.

**Comment by hoshsadiq** [comment]
Without logs I can't do anything. Having said that, this is probably HBBTV issue, since all this apk does is launch HBBTV browser with the relevant login. Please post logs and I can try and dig through it.
