### ISSUE TITLE
My 5 installation error

### ISSUE THREAD

**Issue by Mrmad1966** [hoshsadiq/bravia-youview-player-launchers#20]
Hi, really appreciate your work on this project. Just wondering if you have any idea as to why the My5 APK seems to install fine but when trying to run it I just get a fleeting message that says "errror".

Sorry I don't have more info to offer up at the moment ..

**Comment by hoshsadiq** [comment]
This is probably related to #19. My understanding is My5 has discontinued the link that is used in this app, and launched a new link. I am planning to create a new release for it.

**Comment by Mrmad1966** [comment]
Really appreciate your work on this mate..
Cheers

**Comment by hoshsadiq** [comment]
I had the wrong issue linked earlier, I've updated it. Anyway, version 2.5.0 should fix the issue.
