### ISSUE TITLE
Cannot open apps and record at the same time

### ISSUE THREAD

**Issue by andybog** [hoshsadiq/bravia-youview-player-launchers#22]
Hi, is it possible to look into this limitation again? I can attempt to supply logcat.

I believe the limitation is built in, ie you cannot record and watch catchup at the same time, it is not a fault with your apps, that's just the way it operates. Nevertheless would you be able to see if it's possible to record and watch catchup at the same time?

_Originally posted by @andybog in https://github.com/hoshsadiq/bravia-youview-player-launchers/issues/12#issuecomment-727541911_

**Comment by hoshsadiq** [comment]
If you can reproduce this issue while opening the apps through YouView instead of these apps I've provided, then, as you said, I can't do anything about it. This is just the way YouView behaves. These apps don't do anything fancy besides invoking YouView's mechanism to launch the apps.

**Comment by andybog** [comment]
Yes the issue happens when using the apps through Youview.
I'll take this opportunity to thank you for the apps which allows us to have catch up while Youview is disabled.
