### ISSUE TITLE
Not working on Sony XH90 

### ISSUE THREAD

**Issue by danprice142** [hoshsadiq/bravia-youview-player-launchers#24]
Tried all the shortcuts that was pre made and not working for this tv! has any one got instruction on how to use the app to make my own? or has any been made that will work with this tv?
Thanks Dan

**Comment by hoshsadiq** [comment]
I can't do anything without logs.

**Comment by danprice142** [comment]
Could you please give me some instructions on what to do? I have a windows laptop and can download adb and follow instructions to get the logs needed im just a little unsure on what commands i will have to input to get the logs. 
I am more than willing to make a contribution for your help.
Thanks Dan

**Comment by danprice142** [comment]
or do i sideload the whole zip file to the tv using adb and then try the launchers as i have only sideloaded the individual launchers and the the app?

**Comment by hoshsadiq** [comment]
Yes, have `adb logcat` running, start the app through the YouView app, and then upload the logs into a gist or something, and paste the link here.

**Comment by hoshsadiq** [comment]
Fix is released now, see https://github.com/hoshsadiq/bravia-youview-player-launchers/releases/tag/v3.0.0
