### ISSUE TITLE
No Launcher or shortcut to Britbox Sony 2020 tv 

### ISSUE THREAD

**Issue by danprice142** [hoshsadiq/bravia-youview-player-launchers#26]
I believe this is the URL https://prod-tv.massive-itv.com/yv/index.html

This is the Logcat when launching Britbox from Youview

[outputlog.txt](https://github.com/hoshsadiq/bravia-youview-player-launchers/files/5751450/outputlog.txt)
 
and here are a banner and icon for Britbox 

![Banner (2)](https://user-images.githubusercontent.com/61921129/103300418-b9a03980-49f6-11eb-9e60-9bde2d0f6be6.png)
![Icon (2)](https://user-images.githubusercontent.com/61921129/103300420-bad16680-49f6-11eb-8771-e4cd94d55fb7.png)

**Comment by hoshsadiq** [comment]
Can you test this: [app-britbox-debug.zip](https://github.com/hoshsadiq/bravia-youview-player-launchers/files/5757569/app-britbox-debug.zip)

**Comment by danprice142** [comment]
Works perfect mate thanks a lot and much appreciated
