### ISSUE TITLE
Outdated icons - where did you get current ones?

### ISSUE THREAD

**Issue by lordcodes** [hoshsadiq/bravia-youview-player-launchers#8]
I noticed some of the app icons are out-of-date as they have changed them: iPlayer, All 4 and ITV Hub. The others may be out-of-date as well, I just haven't checked them yet.

I wanted to update the icons and submit a PR, however, I wasn't sure where you got them from? I can get the square icon from Google Play. However, how did you get the banner icons (that are used on TV shelf)?

**Comment by hoshsadiq** [comment]
No where really. I just got them from DDG and Google images. For the banners for several of them they were there on DDG/Google images, but some I had to manually create.

**Comment by lordcodes** [comment]
Okay thanks 👍. Will just do this with the latest images. Just wanted to check first.
